# Generated by Django 4.1.7 on 2023-03-04 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snaphiveApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='category',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
