# Generated by Django 4.1.7 on 2023-03-04 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snaphiveApp', '0003_newsletter_alter_contact_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='others',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
